### ISSUE TITLE
Failed running server on Jetstream

### ISSUE THREAD

**Issue by fdongyu** [fdongyu/DataExchangeAPI#3]
Hi @Seth-Wolfgang, 

When I tried to run your new API (dev branch) on Jetstream, I received the following error. I wonder if you know what may go wrong here. Thanks!

![image](https://github.com/user-attachments/assets/0ce91e8b-9c25-4acf-a4fc-6aed397bf6ac)

**Comment by Seth-Wolfgang** [comment]
I pushed the requirements.txt file. I apologize it wasn't in there.
