### ISSUE TITLE
Failure in running Server

### ISSUE THREAD

**Issue by fdongyu** [fdongyu/DataExchangeAPI#4]
Hi @Seth-Wolfgang , 

When I run "docker compose up" on Jetstream, I received the following error. 
![image](https://github.com/user-attachments/assets/85220151-1337-48f9-9717-749326b87de8)

**Comment by Seth-Wolfgang** [comment]
Either delete that instance `docker rm -f <instance name>` or `docker rmi -f <instance name` or rename server in the compose.yaml file. Maybe that should work?

**Comment by fdongyu** [comment]
Thanks. I see. It turns out "docker compose down" works.
