### ISSUE TITLE
Tests failed on Perlmutter

### ISSUE THREAD

**Issue by fdongyu** [fdongyu/DataExchangeAPI#5]
Hi @Seth-Wolfgang,

Could you explain a bit more on how to run the tests in /dev? The instruction is a bit confusing. 

Could you also perform some test on Perlmutter? When I run the server from /dev and on Jetstream, CyberWater and E3SM on Perlmutter, I could not connect to server. Maybe you could let me know if you had it working before. 

Thanks!

**Comment by Seth-Wolfgang** [comment]
I am actively changing/cleaning up the E3SM client to reflect changes in python code. I will perform tests as soon as possible.

**Comment by fdongyu** [comment]
> I am actively changing/cleaning up the E3SM client to reflect changes in python code. I will perform tests as soon as possible.

Thanks! It would be great to have your new code working on Perlmutter as the top priority. Please let me know if there is anything I can help with for testing.
